const menuButton=document.querySelector('.menu-button');const menu=document.querySelector('.menu');
menuButton?.addEventListener('click',()=>{const open=menu.classList.toggle('open');menuButton.setAttribute('aria-expanded',String(open));});
menu?.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{menu.classList.remove('open');menuButton?.setAttribute('aria-expanded','false');}));
const topbar=document.querySelector('.topbar');addEventListener('scroll',()=>topbar?.classList.toggle('scrolled',scrollY>40),{passive:true});
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target);}}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
const dialog=document.getElementById('videoDialog'),video=document.getElementById('guideVideo'),title=document.getElementById('videoTitle');
document.querySelectorAll('.play-video').forEach(btn=>btn.addEventListener('click',()=>{video.src=btn.dataset.video;title.textContent=btn.dataset.title||'Video guide';dialog.showModal();video.play().catch(()=>{});}));
document.getElementById('closeVideo')?.addEventListener('click',()=>{video.pause();video.removeAttribute('src');video.load();dialog.close();});dialog?.addEventListener('click',e=>{if(e.target===dialog){video.pause();dialog.close();}});
const checks=[...document.querySelectorAll('#checklist input')];checks.forEach((c,i)=>{c.checked=localStorage.getItem(`ov-check-${i}`)==='1';c.addEventListener('change',()=>localStorage.setItem(`ov-check-${i}`,c.checked?'1':'0'));});
document.querySelectorAll('.filter').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.filter').forEach(b=>b.classList.remove('active'));btn.classList.add('active');const f=btn.dataset.filter;document.querySelectorAll('.destination').forEach(card=>card.classList.toggle('hidden',f!=='all'&&!card.dataset.category.split(' ').includes(f)));}));
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('service-worker.js').catch(()=>{}));
